server.port=9070
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/teacher_course
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:123456}
spring.application.name=media-resource-service
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
upload.dir=./uploads
xfyun.spark.apiPassword=${SPARK_API_PASSWORD:}
xfyun.spark.apiUrl=${SPARK_API_URL:https://spark-api-open.xf-yun.com/v1/chat/completions}
xfyun.spark.appId=${SPARK_APP_ID:}
xfyun.spark.model=${SPARK_MODEL:lite}
xfyun.image.appId=${XFYUN_IMAGE_APPID:}
xfyun.image.apiKey=${XFYUN_IMAGE_APIKEY:}
xfyun.image.apiSecret=${XFYUN_IMAGE_APISECRET:}
xfyun.ppt.appId=${XFYUN_PPT_APPID:}
xfyun.ppt.apiSecret=${XFYUN_PPT_APISECRET:}
xfyun.voice.appId=${VOICE_APP_ID:}
xfyun.voice.apiKey=${VOICE_API_KEY:}
xfyun.voice.apiSecret=${VOICE_API_SECRET:}
chatdoc.enabled=true